# -*- coding: utf-8 -*-
"""AlexTele2Data_cb_01_check_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2dxflZ5OFZak21xDhRYeQGhDvAYkN8k
"""

!pip install catboost

#baseline recommend_syst_pro by Alex-Tele2-Data team
import numpy as np
import pandas as pd  #for dataframes
from catboost import CatBoostClassifier
import pickle #for saving model
RS=42  #we will fix random state

#let s connect to google drive with data
from google.colab import drive
drive.mount ('/content/gdrive', force_remount = True)

!ls '../content/gdrive/My Drive/dataset_MADE_2020_taskB'

test_df=pd.read_csv('../content/gdrive/My Drive/dataset_MADE_2020_taskB/test.csv',
                      header=0)
test_df.head()

#let s make lists for checking model
user_id_list=[166,26,41,286,108]	
timestamp_list=[1490944431,1490957371,1490958147,1490971255,1490976836]

#let s load our model 
filename = '../content/gdrive/My Drive/dataset_MADE_2020_taskB/model_recommend_cb01.pickle'
#pickle.dump(pl_clf, open(filename, 'wb'))

pl_clf = pickle.load(open(filename, 'rb'))
temp_item=25
prediction = pl_clf.predict([user_id_list[0],temp_item,timestamp_list[0]])
print(prediction)



модель выдает предикты 1-значит пользователь посетит, пункт temp_item, 0- не посетит.







